Cloud server
tedski999/bangnet pull request #17
Opened 2024-03-13 23:37 UTC by linweilonger

1. add the get_camera_angle api
2. refine swagger api (remove json format)  http://34.241.234.234:8000/swagger/
3. refine the cal Explosion location
4. auto cal and send the result to telegram

2024-03-14 03:58 UTC, cianmawhinney commented
started having a quick look - looks really good! I'll finish off reviewing in the morning

2024-03-14 22:12 UTC, cianmawhinney requested changes
Looks good! I think if the .pyc files and the .db files get removed then it looks good to merge.

2024-03-14 22:12 UTC, cianmawhinney commented on bangnet_cloud/db_opera.py
Is this file just for testing? I take it there's nothing from this file used elsewhere?

2024-03-14 22:12 UTC, cianmawhinney commented on bangnet_cloud/db.sqlite3
Is this an old version of bangnet.db? Or is this different? I don't think I see any other references to it in your code

2024-03-14 22:19 UTC, linweilonger commented on bangnet_cloud/db_opera.py
yes，just for test, I can withdraw the file

2024-03-14 22:20 UTC, linweilonger commented on bangnet_cloud/bangnet.db
This is a local database based on sqlite3, and all our data is stored here.

2024-03-14 22:20 UTC, linweilonger commented on bangnet_cloud/db.sqlite3
yes this file is invalid i will delete it

2024-03-14 22:21 UTC, linweilonger commented on bangnet_cloud/__pycache__/cal_bang_location.cpython-38.pyc
OK I will add .gitignore

2024-03-15 01:03 UTC, cianmawhinney approved these changes

2024-03-15 11:23 UTC, merged